### PR TITLE
Spanish Translation update

### PR DESCRIPTION
**Pull request by HugoJH**
Spanish translation created

### CODE REVIEW

**Comment by Lekensteyn** [comment]
Unrelated files are changed here, if you are still interested could you squash the commits and avoid touching unrelated files? Thanks!

**Comment by HugoJH** [comment]
Don't know why but squashing the commits is getting rather complicated. I prefer to close this request and open another one to avoid any conflicts.

**Comment by Lekensteyn** [comment]
With the git client you can rebase on the latest master and squash with:

    git rebase -i upstream/master

(then replace 'pick' -> 'squash' for all but the first (or last? forgot order))

This assumes that 'upstream' is an up-to-date remote (`git remote add` needs to be done once):

    git remote add upstream https://github.com/pwr/Solaar.git
    git fetch upstream

**Comment by HugoJH** [comment]
Thank you very much for the explanation. I'll have it into account in 
any other time.
Now I've done another pull request.

Hugo

**Pull request closed without merging**
