### PR TITLE
fix openSUSE rpm packages link

### PR DESCRIPTION
**Pull request by rdmitry**

### CODE REVIEW

**Comment by Lekensteyn** [comment]
So "Solaar" is the unofficial package and "solaar" the official one?

Matthias is not the maintainer of the new package, maybe you should change it to your name (Dmitry)?
https://build.opensuse.org/package/view_file/openSUSE:Factory/solaar/solaar.changes?expand=1

**Comment by Lekensteyn** [comment]
@rdmitry Can you give an update? Maybe it should say that it is officially from openSUSE?

**Comment by rdmitry** [comment]
Yes, now all actual openSUSE versions contains Solaar in main repository. Packages solaar-cli for command line interface and solaar for graphical interface.

**Comment by jrbenito** [comment]
@rdmitry ,

Are you able to solve conflicts for this PR?

**Comment by Lekensteyn** [comment]
No response, closing.

**Pull request closed without merging**
