### PR TITLE
Fix zh_TW translation (nplural=1)

### LINKED ISSUE #500: FTBFS: nplurals = 1 but some messages have 2 plural forms
Ubuntu 19.04 disco
solaar 0.9.2-259-gc07c115 (git20190130.c07c115)
python2.7: 2.7.15-8

Building with:
```
cd packaging
echo ------------------------------
echo Changing DPKG_BUILPACKAGE_OPTS
echo ------------------------------
sed -Ei "s|DPKG_BUILPACKAGE_OPTS=\"-b -us -uc\"|DPKG_BUILPACKAGE_OPTS=\"-i -I --no-sign --build=binary -m'<manciot.jeanchristophe@gmail.com>'\"|g" build_deb.sh

echo ---------------------------------------
echo Forcing debchange to accept our version
echo ---------------------------------------
sed -Ei "s|/usr/bin/debchange|/usr/bin/debchange -b|g" build_deb.sh

echo --------
echo Building
echo --------
./build_deb.sh
```
leads to:
```
/usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'install_requires'
  warnings.warn(msg)
/usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'install_requires'
  warnings.warn(msg)
/media/actionmystique/SAMSUNG5-Shared/home/actionmystique/src/Logitech/git-solaar/po/zh_TW.po:7: nplurals = 1...
/media/actionmystique/SAMSUNG5-Shared/home/actionmystique/src/Logitech/git-solaar/po/zh_TW.po:203: ...but some messages have 2 plural forms
/usr/bin/msgfmt: found 1 fatal error
```

### PR DESCRIPTION
**Pull request by pdecat**
Resolves #500 #513

### CODE REVIEW

**Comment by pdecat** [comment]
Hi @PeterDaveHello, as the author of https://github.com/pwr/Solaar/pull/485, could you please review this PR?

**Comment by pdecat** [comment]
Thanks!

**Comment by cement-head** [comment]
So how do I get this file into the latest pull from git so that I can compile?

**Comment by pdecat** [comment]
@cement-head if you only want this fix, in your existing git clone do:

```
# git remote add fork-pdecat git@github.com:pdecat/Solaar.git
# git fetch --all
# git cherry-pick ebbb54758bd17dcadb58dcbc2ba52518432d8bfb
```

**Comment by Lekensteyn** [comment]
Thanks for your work, merging!

**Pull request merged**
