### PR TITLE
Fix incorrect device status detection

### PR DESCRIPTION
**Pull request by SonicFrog**
This should fix issue #405  

Signed-off-by: Ogier Bouvier <obouvier@logitech.com>

### CODE REVIEW

**Comment by cement-head** [comment]
So if someone signed off on this; is it in the master?

**Comment by SonicFrog** [comment]
I guess some testing other than my own would be needed first.

**Comment by Lekensteyn** [comment]
This is actually a revert of a4b71944901410c5bfed5a137ed69cd4323a8ff5 (merged in #382), do you have any comments on that?

**Comment by SonicFrog** [comment]
As mentioned in the comment notification 0x41 indicates a connection, not a necessarily a new pairing. When doing some debugging the notification handler consistently crashed when an already known device came online after Solaar was started since it tried to register it as though it was new.  

I haven't encountered any problems on Gentoo with this, though I'll do some Fedora testing, now that you mention it fixed a problem on Fedora

**Comment by SonicFrog** [comment]
So, after some Fedora testing I couldn't manage to reproduce the bug mentionned in https://github.com/pwr/Solaar/commit/a4b71944901410c5bfed5a137ed69cd4323a8ff5
Using three different kind of receivers with a mix of devices, Solaar never failed to start and detected device status correctly.

**Comment by noabody** [comment]
My use-case scenario involves a [Pluggable usb2-switch2](https://plugable.com/products/usb2-switch2/) K360 keyboard and M510v2 mouse.  The switch connects my two desktops to a USB 2.0 Hub to which the Unifying receiver is connected.

With this code in place, after a few minutes of inactivity, the mouse seems to sleep and solaar indicates no hardware is connected (blue tray icon turns yellow).  Any combination of the receiver and the switch indicates this problem, but there is no issue with the switch removed (even a single computer and the receiver as the only devices plugged into the switch.

**Pull request closed without merging**
