### PR TITLE
Fix merge conflicts, add Logitech G700 and G700s Gaming mouse support, add croatian translation

### PR DESCRIPTION
**Pull request by muzena**

### CODE REVIEW

**Comment by bipson** [comment]
Hm, this is somewhat a clone of #182, right? Just for your information, you can update your pull requests by pushing new commits to the respective branch (the 'from'-branch, where you opened your pull request from), and this would be preferable.
Also, you did not address the comments in #182, and this pull request has the same issues pointed out there, I think.
Just trying to help.

**Comment by muzena** [comment]
Yes this is https://github.com/pwr/Solaar/pull/182 clone, I try to fix it but always had conflict, then I delete and made new fork without conflicts.

**Comment by muzena** [comment]
@Lekensteyn 
Can you merge this pull request after such a long time, or there is some problem with this pull request?

**Comment by Lekensteyn** [comment]
Can you remove the unrelated changes in https://github.com/pwr/Solaar/pull/210/commits/34058725bf4aeb513429d5787ae6e4385852e59f? There are more pending translations, I guess it should be refreshed before release.

**Comment by muzena** [comment]
@Lekensteyn 
Is now ok?

**Comment by muzena** [comment]
@Lekensteyn 
Please, merge this.

**Comment by Lekensteyn** [comment]
There are many changes here, can you squash the commits into one and remove unrelated commits? Ideally you only have commits for the translations and mice.

Sorry for delaying this for so long.

**Comment by muzena** [comment]
@Lekensteyn 
I don't understand what unrelated commits to remove?
It is translation file, G700 and G700s support, without udev files won't start on ubuntu and derivates,
And I add info in docs/devices.md  file about these mices
And translated hr string in shortcut .desktop file to.
So what of these files to remove?

**Comment by jrbenito** [comment]
@muzena, my two cents are

- squash  all commits related to G700 and G700s into a single commit, no matter if they touch code or documents
- squash all translations (for a single language) together (more than one commit if you touch multiple languages, I believe it is better for history)

Also, unrelated contributions would (preferably) be done on separate PRs, if everything is related than one PR is ok. Lekensteyn might have other suggestions and he is the voice to be heard not me :)

**Comment by Lekensteyn** [comment]
When I try to merge your changes, I see that there are changed to the Spanish and other translation files which is not related to the Croatian ones (this is what I meant by unrelated, together with the strange udev rule change).

If you are OK with that, I could try to squash the changes and merge them and save you some effort?

**Comment by muzena** [comment]
@Lekensteyn 
Aha, I revert this commits before, this files are excluded from this PR as you said before.
I don't see them up in 'Files changed' tab.
Ok i will made all in new one commit then.

**Comment by Lekensteyn** [comment]
Preferably one commit for the translation, one commit for the new device. Thanks :)

If you have difficulties, let me know and I will try to squash some changes together.

**Pull request closed without merging**
