### PR TITLE
Added support for MintX icon set (for Linux Mint integration)

### PR DESCRIPTION
**Pull request by cschreib**
This pull request provides support for the default icon theme in Linux Mint (tested in Cinnamon edition). See the example screenshot below.

screenshot-area-2016-10-22-135037

### CODE REVIEW

**Comment by Lekensteyn** [comment]
This seems the GNOME icon theme (Adwaita), maybe you can rename it to "gnome" instead of "mint"?

**Comment by cschreib** [comment]
You are correct, however there is already a "gnome" icon set configured in Solaar, which is looking for standard icons instead of the scalable "symbolic" version.
Standard icon (battery-caution-charging): 
battery-caution-charging
Symbolic icon (battery-caution-charging-symbolic):
battery-caution-charging-symbolic

Maybe "gnome_symbolic" then?

**Comment by Lekensteyn** [comment]
`gnome_symbolic` looks good based on that page, is the text still current though? Last commit was done in 2014.

**Comment by Lekensteyn** [comment]
Hi, what is the status of this PR? Is it still necessary?

**Comment by cschreib** [comment]
My desktop is still running the same version of Linux Mint as when I first created the pull request, so for me this would still be needed. I do not know if newer versions of Linux Mint behave differently, but I would expect the situation would be the same if I were to upgrade.

**Comment by Lekensteyn** [comment]
It does not hurt I guess, in the worst case it would look different. Merging!

**Comment by arigit** [comment]
@Lekensteyn this PR broke solaar GUI in Ubuntu / 18.04 - it causes it to crash after a few minutes of use, please see #444 for details. Can the PR merge be reverted?

**Comment by zfil** [comment]
@Lekensteyn funny I'm using Mint 18.3 and this PR makes the battery tray icon disappear.
Reverting this PR fixes the issue.

**Pull request merged**
