### PR TITLE
Add MX Master 2S descriptor

### PR DESCRIPTION
**Pull request by Valantin**
Add descriptor for MX Master 2S to support High Resolution Wheel, correct charge level and DPI configuration

### CODE REVIEW

**Comment by keradus** [comment]
looks great :+1:

**Comment by arigit** [comment]
@Lekensteyn can this get merged?

**Comment by Lekensteyn** [comment]
Merged, thanks for PR!

**Comment by sheepdestroyer** [comment]
For me the charge level is always reported as "50%" for my MX Master 2S

**Pull request merged**
