### PR TITLE
Adding Logitech mx 1100 cordless laser mouse to discriptors

### PR DESCRIPTION
**Pull request by emerham**
Solaar is working with the nano receiver, battery info showing just missing the description about the mouse. This adds the MX 1100 to the list.

### CODE REVIEW

**Comment by Lekensteyn** [comment]
Can you also update docs/devices.md? Thanks!

**Comment by emerham** [comment]
Ok So I've been looking and the Docs and found that the mouse has some options the original pull does. So I'm updating my pull and adding in docs as well.

**Comment by emerham** [comment]
So I added smooth scrolling and horizontal scrolling options. When running `solaar show` it is unable to find the power switch information. Is there some debug flag to print the register that it found from the receiver to update the power switch location?

**Comment by Lekensteyn** [comment]
The power switch location is only available on newer devices if I remember correctly. Maybe it is also known for the older versions, but the registers for HID++ 1.0 are mostly not officially documented. Some reverse-engineered docs are at https://git.lekensteyn.nl/ltunify/tree/registers.txt.

Thanks for the PR!

**Pull request merged**
