### PR TITLE
Fix #324

### LINKED ISSUE #324: Missing system-tray icon on Wayland (Fedora 25)
With Fedora's default wayland desktop, Solaar's system try icon is not visible, hence the app can't be invoked once it was launched

This is with the latest git code. I see some warnings when launching from a terminal

> solaar
/usr/lib/python2.7/site-packages/solaar/gtk.py:34: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '3.0') before import to ensure that the right version gets loaded.
  __import__(module)
/usr/lib/python2.7/site-packages/solaar/ui/notify.py:33: PyGIWarning: Notify was imported without specifying a version first. Use gi.require_version('Notify', '0.7') before import to ensure that the right version gets loaded.
  from gi.repository import Notify
/usr/lib/python2.7/site-packages/solaar/ui/tray.py:148: PyGIWarning: AppIndicator3 was imported without specifying a version first. Use gi.require_version('AppIndicator3', '0.1') before import to ensure that the right version gets loaded.
  from gi.repository import AppIndicator3

### PR DESCRIPTION
**Pull request by moceap**

### CODE REVIEW

**Comment by Lekensteyn** [comment]
Interesting, where did you find this (any documentation or other example)? I think it is also the wrong file, since when you start solaar from a shell you will not have that envvar.

**Comment by moceap** [comment]
Lot of docs:

https://www.google.com/search?q=GDK_BACKEND%3Dx11&ie=utf-8&oe=utf-8

**Comment by arigit** [comment]
Confirmed that this fixes the problem, when launching solaar from the Application launcher. The icon is still missing though when launching solaar from command line, so this is more of a workaround. With X11, the tray icon is present regardless of how solaar is launched

**Comment by jhoblitt** [comment]
This still seems to be a problem under f27 with wayland.

**Comment by Lekensteyn** [comment]
Thanks for the PR, but I think that this change is not sufficient. The code needs some love for Wayland support (and to make it work for Plasma). I'll be closing this issue for now (in preparation of moving to a new repo), in meantime you could edit the desktop file manually.

**Pull request closed without merging**
