### PR TITLE
Mk270 Combo information and descritptors

### LINKED ISSUE #234: [046d:c534] with mouse M185 & keyboard K270
[Bus 001 Device 003: ID **046d:c534** Logitech, Inc.]

Solaar doesn't recognize this receiver.

```
usb 1-3: New USB device found, idVendor=046d, idProduct=c534
usb 1-3: New USB device strings: Mfr=1, Product=2, SerialNumber=0
usb 1-3: Product: USB Receiver
usb 1-3: Manufacturer: Logitech
usbcore: registered new interface driver usbhid
usbhid: USB HID core driver
Logitech USB Receiver as /devices/pci0000:00/0000:00:14.0/usb1/1-3/1-3:1.0/0003:046D:C534.0001/input/input4
hid-generic 0003:046D:C534.0001: input,hidraw0: USB HID v1.11 Keyboard [Logitech USB Receiver] on usb-0000:00:14.0-3/input0
input: Logitech USB Receiver as /devices/pci0000:00/0000:00:14.0/usb1/1-3/1-3:1.1/0003:046D:C534.0002/input/input5
hid-generic 0003:046D:C534.0002: input,hiddev0,hidraw1: USB HID v1.11 Mouse [Logitech USB Receiver] on usb-0000:00:14.0-3/input1
```

### PR DESCRIPTION
**Pull request by jrbenito**
*** This PR depends on #337 

Adds support for MK 270 Combo. 

K270 non unifying
M185 non unifying (older version than #337)

fixes #234

### CODE REVIEW

**Comment by Lekensteyn** [comment]
uh oh, it has conflicts. did I do something wrong?

**Comment by jrbenito** [comment]
> uh oh, it has conflicts. did I do something wrong?

No! It is probably due to the order I sent PRs. Let me resolve and commit again.

Done!

**Comment by Lekensteyn** [comment]
ehm, I caused a conflict again :(

**Comment by jrbenito** [comment]
@Lekensteyn , solved!

**Pull request merged**
