### PR TITLE
Support MX Air Receiver

### PR DESCRIPTION
**Pull request by homburg**
- Add udev rule for mx air receiver product id
- Add specific reciever naming for MX Air Receiver

### CODE REVIEW

**Comment by Lekensteyn** [comment]
Is this the product you are adding support for?
http://support.logitech.com/en_us/product/mx-air-rechargeable-cordless-air-mouse

I can't find the technical specifications for this, the previous custhelp site is gone (example page is http://archive.is/fwhEU). Does your device work with other Unifying devices, can you post the output of `solaar show`?

**Comment by homburg** [comment]
Yes, that is the product.

The receiver is specific to the mx air mouse and the mx air mouse cannot be used with a unifying receiver.

As far as I know the receiver is only compatible with the mx air mouse.

Output from `solaar show`
```
  1: MX Air
     Codename     : MX Air
     Kind         : mouse
     Wireless PID : 100E
     Protocol     : HID++ 1.0
     Serial number: 0DB169BC
          Firmware: 65.00.B0068
             Other: 01.02
     The power switch is located on the (unknown).
     Notifications: (none).
     Battery: 95%, discharging.
```

`lsusb`
```
Bus 004 Device 007: ID 046d:c525 Logitech, Inc. MX Revolution Cordless Mouse
```

Hard to see, but it says "MX Air" on the front bottom.
img_20160604_151410

**Comment by Lekensteyn** [comment]
Looks good, can you also try `tools/scan-registers.sh` and see if there are additional settings that can be modified?

If you are interested in just battery reporting, can you try to add this udev rule:
```
SUBSYSTEM=="usb", ATTRS{idVendor}=="046d", ATTRS{idProduct}=="c525", ENV{UPOWER_BATTERY_TYPE}="lg-wireless"
```
restart upowerd and invoke `upower -d`. Does it show the battery level for your device? This information would be made available to all desktop applications relying on upower for battery reporting, not just Solaar.

**Comment by homburg** [comment]
`tools/scan-registers.sh 1` (through 6) says

```
!! No HID++ receiver found.
# Warning: hidconsole API got changed - unrecognized output
!! No HID++ receiver found.
!! No HID++ receiver found.
```

**Comment by homburg** [comment]
`upower -d` output (after adding udev rule and restarting the `upower` service.

```
Device: /org/freedesktop/UPower/devices/line_power_ADP1
  native-path:          ADP1
  power supply:         yes
  updated:              man 06 jun 2016 18:39:06 CEST (83 seconds ago)
  has history:          no
  has statistics:       no
  line-power
    warning-level:       none
    online:              yes
    icon-name:          'ac-adapter-symbolic'

Device: /org/freedesktop/UPower/devices/battery_BAT0
  native-path:          BAT0
  vendor:               Sony Corp.
  power supply:         yes
  updated:              man 06 jun 2016 18:39:06 CEST (83 seconds ago)
  has history:          yes
  has statistics:       yes
  battery
    present:             yes
    rechargeable:        yes
    state:               fully-charged
    warning-level:       none
    energy:              44,16 Wh
    energy-empty:        0 Wh
    energy-full:         44,16 Wh
    energy-full-design:  62,64 Wh
    energy-rate:         0 W
    percentage:          100%
    capacity:            70,4981%
    technology:          lithium-ion
    icon-name:          'battery-full-charged-symbolic'
  History (charge):
    1465231146	0,000	unknown
  History (rate):
    1465231146	0,000	unknown

Device: /org/freedesktop/UPower/devices/DisplayDevice
  power supply:         yes
  updated:              man 06 jun 2016 18:39:06 CEST (83 seconds ago)
  has history:          no
  has statistics:       no
  battery
    present:             yes
    state:               fully-charged
    warning-level:       none
    energy:              44,16 Wh
    energy-full:         44,16 Wh
    energy-rate:         0 W
    percentage:          100%
    icon-name:          'battery-full-charged-symbolic'

Daemon:
  daemon-version:  0.99.4
  on-battery:      no
  lid-is-closed:   no
  lid-is-present:  yes
  critical-action: HybridSleep
```

**Comment by Lekensteyn** [comment]
What driver is reported by `lsusb -t` for the Logitech device interfaces? Can you try this:
```diff
--- a/lib/hidapi/hidconsole.py
+++ b/lib/hidapi/hidconsole.py
@@ -148,7 +148,8 @@
 	device = args.device
 	if args.hidpp and not device:
 		for d in _hid.enumerate(vendor_id=0x046d):
-			if d.driver == 'logitech-djreceiver':
+			# logitech-hidpp-device is the new name since Linux 3.19
+			if d.driver in ('logitech-djreceiver', 'logitech-hidpp-device'):
 				device = d.path
 				break
 		if not device:
```

**Comment by homburg** [comment]
## `lsusb`
```
Bus 004 Device 002: ID 8087:0024 Intel Corp. Integrated Rate Matching Hub
Bus 004 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 001 Device 002: ID 046d:c525 Logitech, Inc. MX Revolution Cordless Mouse
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 003 Device 004: ID 05ca:18c0 Ricoh Co., Ltd 
Bus 003 Device 006: ID 0489:e036 Foxconn / Hon Hai 
Bus 003 Device 002: ID 8087:0024 Intel Corp. Integrated Rate Matching Hub
Bus 003 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
```
## `lsusb -t`
```
/:  Bus 04.Port 1: Dev 1, Class=root_hub, Driver=ehci-pci/2p, 480M
    |__ Port 1: Dev 2, If 0, Class=Hub, Driver=hub/6p, 480M
/:  Bus 03.Port 1: Dev 1, Class=root_hub, Driver=ehci-pci/2p, 480M
    |__ Port 1: Dev 2, If 0, Class=Hub, Driver=hub/6p, 480M
        |__ Port 2: Dev 6, If 0, Class=Wireless, Driver=btusb, 12M
        |__ Port 2: Dev 6, If 1, Class=Wireless, Driver=btusb, 12M
        |__ Port 3: Dev 4, If 0, Class=Video, Driver=uvcvideo, 480M
        |__ Port 3: Dev 4, If 1, Class=Video, Driver=uvcvideo, 480M
/:  Bus 02.Port 1: Dev 1, Class=root_hub, Driver=xhci_hcd/2p, 5000M
/:  Bus 01.Port 1: Dev 1, Class=root_hub, Driver=xhci_hcd/2p, 480M
    |__ Port 1: Dev 2, If 0, Class=Human Interface Device, Driver=usbhid, 12M
    |__ Port 1: Dev 2, If 1, Class=Human Interface Device, Driver=usbhid, 12M

```

**Comment by homburg** [comment]
I tried running and inspecting `./tools/hidconsole --hiddp`

`d.driver` hidconsole.py appears to be `hid-generic`

**Comment by Lekensteyn** [comment]
Hi @homburg , as I am preparing for a migration to a new repo, I found this open PR. Is it still needed?

If so, please resolve the merge conflict and add device info to `doc/devices/` (see the contents of that directory for inspiration). Thanks!

**Comment by homburg** [comment]
@Lekensteyn I'll take a look at it 👍

**Comment by homburg** [comment]
Good to go 👍

**Pull request closed without merging**
